### ISSUE TITLE
Duplicate entry 'associationtype' for categories

### ISSUE THREAD

**Issue by tpokorra** [basxsoftwareassociation/basxconnect#7]
I get this error in my nightly test build:
https://lbs.solidcharity.com/package/basx/basxconnect/basxconnect-test#main_centos/8/amd64

```
Applying core.0017_category_association_type...Traceback (most recent call last):
[00:05:34]   File "/home/django/basxconnect_demo/.venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
[00:05:34]     return self.cursor.execute(sql, params)
[00:05:34]   File "/home/django/basxconnect_demo/.venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
[00:05:34]     return self.cursor.execute(query, args)
[00:05:34]   File "/home/django/basxconnect_demo/.venv/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
[00:05:34]     res = self._query(query)
[00:05:34]   File "/home/django/basxconnect_demo/.venv/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
[00:05:34]     db.query(q)
[00:05:34]   File "/home/django/basxconnect_demo/.venv/lib64/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
[00:05:34]     _mysql.connection.query(self, query)
[00:05:34] MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'associationtype' for key 'slug'")
```

The reason is this commit: https://github.com/basxsoftwareassociation/basxconnect/commit/37c2cdb2c03314c1a65a7447e32b9eb94a4e2d22#diff-ce51dd213b60c06bc89425fe749aa3807a3d17bb7084e4ae77d145604ab5411a

The category associationtype is now already added in migration 0006_preload_categories.py.
The category associationtype does not need to be added anymore in https://github.com/basxsoftwareassociation/basxconnect/blob/main/basxconnect/core/migrations/0017_category_association_type.py

I am not sure if the commit was a mistake, or if 0017_category_association_type.py should be adjusted.

**Comment by saemideluxe** [comment]
Ok, thx. Btw. we should think about organizing initial data with fixtures instead of migrations. That way it would be easy to provide initial data in different languages.
